// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1S4lNbD4q5uDDFl9XtbujnS6tSzDf7U',
    appId: '1:621211987093:web:7452da8e86ba3add00bf9c',
    messagingSenderId: '621211987093',
    projectId: 'pix-wiz',
    authDomain: 'pix-wiz.firebaseapp.com',
    storageBucket: 'pix-wiz.appspot.com',
    measurementId: 'G-EEMEHBJGL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0T-qTqVaLDz51Vqr2WJli2NmzUDqOZe8',
    appId: '1:621211987093:android:f344ab1dc7f851be00bf9c',
    messagingSenderId: '621211987093',
    projectId: 'pix-wiz',
    storageBucket: 'pix-wiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Gq6kowkW8rN-OMLnIDDQiVZoqX5seVA',
    appId: '1:621211987093:ios:0a7b6bb036a8901900bf9c',
    messagingSenderId: '621211987093',
    projectId: 'pix-wiz',
    storageBucket: 'pix-wiz.appspot.com',
    iosBundleId: 'com.example.pixWiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Gq6kowkW8rN-OMLnIDDQiVZoqX5seVA',
    appId: '1:621211987093:ios:2f93dd4e56b1a56100bf9c',
    messagingSenderId: '621211987093',
    projectId: 'pix-wiz',
    storageBucket: 'pix-wiz.appspot.com',
    iosBundleId: 'com.example.pixWiz.RunnerTests',
  );
}
